name: CoreagesCMD
version: '${project.version}'
main: com.coreages.coreagescmd.CoreagesCMD
api-version: '1.20'
commands:
  sb:
    description: Clear the invisible armor_stand
    usage: /<command>
    permission: coreages.command.sb
    permission-message: No Permission
  sbcount:
    description: Count the number of invisible armor_stand
    usage: /<command>
    permission: coreages.command.sbcount
    permission-message: No Permission
  sblook:
    description: Count the number of invisible armor_stand, and inspect armor_stand' local.
    usage: /<command>
    permission: coreages.command.sblook
    permission-message: No Permission